"""
SkyGuard AI — Phase 2d: Evaluation.

Scores every reading in a labeled (_labeled.csv) dataset against the
trained model + rule engine, and compares against ground truth to
compute real precision/recall/F1.

OVERFITTING CAUTION (Day 61) -- read this before trusting the numbers:
This evaluation's "ground truth" anomalies were generated by OUR OWN
anomaly_injector.py. A strong score here proves the pipeline can detect
the SPECIFIC fault patterns we ourselves defined -- it does NOT prove
the system would catch a real, novel AWS sensor failure. Report these
numbers as "performance against injected synthetic faults, our best
available proxy for ground truth" -- not as "proven real-world
accuracy."

BUG FIX LOG (keep in sync with detect.py's, and with each other):

  1. IS_ANOMALY_THRESHOLD raised 40 -> 55, FROZEN check's prefix
     mapping fixed -- see detect.py's log #1-2.

  2. GROUND-TRUTH LEAKAGE FIX: features.py's add_temporal_features()
     masks is_anomaly==True rows OUT of their own rolling baseline --
     correct for train.py/detect.py (which never see is_anomaly at
     all), WRONG for evaluation, which was passing the labeled frame
     straight through and getting a third, different feature
     computation neither train.py nor detect.py would ever produce.
     Fixed: is_anomaly/fault_type stripped before featurizing, kept as
     `labels`, reattached by merging on (station_id, timestamp) --
     NEVER by row position, since build_feature_matrix regroups rows
     per-station internally.

  3. FROZEN/DRIFT RULE REPLACED to match detect.py's #3-4: short
     raw-diff + persistence for frozen, 24h-delta + small-roc for
     drift, thresholds read from the model artifact instead of
     hardcoded constants.

  4. SPATIAL FEATURE TRAIN/SERVE MISMATCH (found while diagnosing #3):
     this module evaluates one _labeled.csv (one station) at a time.
     add_spatial_features needs >=2 stations of the SAME cluster
     present in the SAME call to compute anything real -- with exactly
     1 station present, every cluster's spatial_*_inconsistency
     silently fell back to the neutral 0.0 in EVERY evaluation run this
     project has done, while train.py (which fits on the full
     multi-station file) computed real, non-zero spatial values for
     those same columns. That's a genuine, uncredited train/serve
     mismatch on 3 of the model's 22 features, likely a real
     contributor to weak precision across every prior eval pass, not
     just the frozen/drift issue. FIXED: evaluate_all() combines every
     *_labeled.csv into ONE dataframe before featurizing (so clusters
     have real neighbor context), then splits back out by source file
     only for per-station reporting.

  5. TIERED RULE FLOOR added: physical_bounds/dropout (certain facts)
     keep the 85 floor; frozen_value/drift (calibrated statistical
     guesses) now get a lower 65 floor instead of sharing 85. This is
     the structural fix for why every rule-threshold recalibration this
     project went through caused a dramatic precision swing rather than
     a mild one -- soft rules were getting hard-rule confidence. A
     miscalibrated soft rule now degrades to a medium-severity flag
     instead of a false critical.     
"""

import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

sys.path.append(str(Path(__file__).parent.parent))
from model.features import (
    build_feature_matrix,
    FEATURE_COLUMNS,
    RULE_ONLY_PREFIXES,
    DRIFT_LOOKBACK_HOURS,
    get_threshold,
)

DATA_DIR = Path(__file__).parent.parent / "data"
ARTIFACTS_PATH = Path(__file__).parent.parent / "model_artifacts" / "isolation_forest.pkl"

PHYSICAL_BOUNDS = {
    "temperature_c": (-10.0, 55.0),
    "pressure_hpa": (850.0, 1080.0),
    "humidity_pct": (0.0, 100.0),
}


IS_ANOMALY_THRESHOLD = 75  # must match detect.py's -- see BUG FIX LOG #1
MODEL_ONLY_THRESHOLD = 90
HARD_RULE_FLOOR = 85.0     # must match detect.py's HARD_RULE_FLOOR -- see BUG FIX LOG #6
SOFT_RULE_FLOOR = 75.0     # must match detect.py's SOFT_RULE_FLOOR -- see BUG FIX LOG #6
FROZEN_PERSISTENCE_READINGS = 3  # was 4 -- corrected math: freeze_length=randint(3,7)
# in anomaly_injector.py means only freeze_length CONSECUTIVE tiny-diff rows exist
# (idx+1..end_idx), NOT freeze_length+1 -- row idx itself is the transition INTO
# the freeze (frozen_value assigned from idx's own original reading), so its
# consec_diff vs idx-1 is normal-sized, not tiny. Persistence=4 could never fire
# on the minimum freeze_length=3 case (only 3 tiny diffs available), which is
# exactly why recall collapsed 72.4%->43.1%. 3 is the correct ceiling.
DRIFT_PERSISTENCE_READINGS = 3  # must match detect.py's -- same reasoning, see detect.py's comment

def vectorized_model_scores(featured: pd.DataFrame, artifact: dict) -> np.ndarray:
    """Same math as detect.py's _model_score_to_pct, applied to every row at once."""
    model = artifact["model"]
    X = featured[artifact["feature_columns"]].values.astype(np.float64)
    raw_scores = model.decision_function(X)
    z = (0.0 - raw_scores) / (artifact["training_score_std"] + 1e-9)
    pct = 100 / (1 + np.exp(-1.5 * z))
    return np.clip(pct, 0, 100)


def vectorized_rule_flags(featured: pd.DataFrame, artifact: dict) -> tuple:
    """
    Same rule logic as detect.py's _rule_checks, vectorized. Returns
    (hard_fired, soft_fired) SEPARATELY rather than one combined
    boolean -- see detect.py's BUG FIX LOG #6 / HARD_RULE_TYPES /
    SOFT_RULE_TYPES. physical_bounds/dropout are certain; frozen_value/
    drift are calibrated statistical guesses and get a lower score
    floor in the fusion step below, so they must stay distinguishable
    here rather than being OR'd into a single flag the way the old
    version did.

    Reads raw temp/pressure/humidity and rule-only columns straight off
    `featured` rather than a separately-tracked raw dataframe.

    Frozen/drift checks are computed per-station, since `featured` here
    is a MULTI-STATION combined frame (see evaluate_all) -- "2
    consecutive readings" must mean 2 consecutive readings of the SAME
    station.
    """
    thresholds = artifact.get("rule_thresholds")
    if thresholds is None:
        raise KeyError(
            "artifact missing 'rule_thresholds' -- it was saved by an older train.py, "
            "before calibrate_rule_thresholds() was added. Retrain first."
        )

    hard_fired = pd.Series(False, index=featured.index)
    frozen_fired = pd.Series(False, index=featured.index)
    drift_fired = pd.Series(False, index=featured.index)
    spike_fired = pd.Series(False, index=featured.index)

    # HARD: physical_bounds + dropout
    for param, (low, high) in PHYSICAL_BOUNDS.items():
        hard_fired |= (featured[param] < low) | (featured[param] > high)
    for param in PHYSICAL_BOUNDS:
        hard_fired |= featured[param].isna()
    ordered = featured.sort_values(["station_id", "timestamp"])

    for _, prefix in RULE_ONLY_PREFIXES:
        consec_col = f"{prefix}_consec_diff"

        # Per-station frozen threshold, aligned row-by-row.
        frozen_thresholds = ordered["station_id"].map(
            lambda sid: get_threshold(
                thresholds, "frozen", prefix, sid
            )
        )

        below_threshold = (
            ordered[consec_col] < frozen_thresholds
        ).fillna(False)

        # Require FROZEN_PERSISTENCE_READINGS consecutive hits
        # within the SAME station.
        frozen = below_threshold.groupby(
            ordered["station_id"]
        ).transform(
            lambda s: (
                s.astype(int)
                .rolling(
                    FROZEN_PERSISTENCE_READINGS,
                    min_periods=FROZEN_PERSISTENCE_READINGS,
                )
                .sum()
                .eq(FROZEN_PERSISTENCE_READINGS)
            )
        )

        frozen_fired |= frozen.reindex(
            frozen_fired.index
        ).fillna(False).astype(bool)

        delta_col = f"{prefix}_{DRIFT_LOOKBACK_HOURS}h_delta"
        roc_col = f"{prefix}_roc_1h"

        # Per-station thresholds.
        drift_thresholds = ordered["station_id"].map(
            lambda sid: get_threshold(
                thresholds, "drift", prefix, sid
            )
        )

        roc_small_thresholds = ordered["station_id"].map(
            lambda sid: get_threshold(
                thresholds, "roc_small", prefix, sid
            )
        )

        drift_condition = (
            ordered[delta_col].abs() > drift_thresholds
        ) & (
            ordered[roc_col].abs() < roc_small_thresholds
        )

        drift_condition = drift_condition.fillna(False)

        # Require DRIFT_PERSISTENCE_READINGS consecutive hits
        # within the SAME station.
        drift = drift_condition.groupby(
            ordered["station_id"]
        ).transform(
            lambda s: (
                s.astype(int)
                .rolling(
                    DRIFT_PERSISTENCE_READINGS,
                    min_periods=DRIFT_PERSISTENCE_READINGS,
                )
                .sum()
                .eq(DRIFT_PERSISTENCE_READINGS)
            )
        )

        drift_fired |= drift.reindex(
            drift_fired.index
        ).fillna(False).astype(bool)

        dev_col = f"{prefix}_deviation"

        spike_thresholds = ordered["station_id"].map(
            lambda sid: get_threshold(
                thresholds, "spike", prefix, sid
            )
        )

        spike = (
            ordered[dev_col].abs() > spike_thresholds
        ).fillna(False)

        spike_fired |= spike.reindex(
            spike_fired.index
        ).fillna(False)

    soft_fired = frozen_fired | drift_fired | spike_fired
    return hard_fired, soft_fired, {"frozen": frozen_fired, "drift": drift_fired, "spike": spike_fired}

def _featurize_and_score(input_df: pd.DataFrame, metadata, artifact: dict, mask_col: str = None):
    """
    One full featurize -> complete-row-filter -> score pass. If mask_col
    is given, input_df must carry a boolean column of that name, which
    gets renamed to "is_anomaly" so add_temporal_features' exclude_mask
    picks it up (see features.py) -- this is how PASS 2 masks OUT rows
    a prior pass predicted anomalous from the rolling baseline, without
    touching real ground truth.
    """
    feat_df = input_df if mask_col is None else input_df.rename(columns={mask_col: "is_anomaly"})
    meta = metadata if metadata is not None else pd.DataFrame(columns=["station_id", "cluster_id"])
    result = build_feature_matrix(feat_df, meta)
    if mask_col is not None:
        result = result.drop(columns=["is_anomaly"], errors="ignore")

    for col in ["spatial_temp_inconsistency", "spatial_pressure_inconsistency", "spatial_humidity_inconsistency"]:
        if col in result.columns:
            result[col] = result[col].fillna(0.0)

    complete = result[FEATURE_COLUMNS].notna().all(axis=1)
    n_dropped = int((~complete).sum())
    result = result[complete].reset_index(drop=True)

    mp = vectorized_model_scores(result, artifact)
    hf, sf, soft_breakdown = vectorized_rule_flags(result, artifact)
    sp = np.where(
        hf,
        np.maximum(HARD_RULE_FLOOR, mp),
        np.where(sf, np.maximum(SOFT_RULE_FLOOR, mp), mp)
    )
    predicted = hf | sf | (mp >= MODEL_ONLY_THRESHOLD)
    
    return result, mp, hf, sf, sp, predicted, n_dropped, soft_breakdown



def _score_and_report(featured: pd.DataFrame, label: str, n_dropped: int) -> dict:
    ground_truth = featured["is_anomaly"]
    fault_type = featured["fault_type"]
    predicted = featured["__predicted"]

    tp = int((predicted & ground_truth).sum())
    fp = int((predicted & ~ground_truth).sum())
    fn = int((~predicted & ground_truth).sum())
    tn = int((~predicted & ~ground_truth).sum())

    precision = tp / (tp + fp) if (tp + fp) > 0 else float("nan")
    recall = tp / (tp + fn) if (tp + fn) > 0 else float("nan")
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else float("nan")

    print(f"\n=== {label} ===")
    print(f"({n_dropped} warm-up rows excluded from evaluation)")
    print(f"Confusion matrix: TP={tp}  FP={fp}  FN={fn}  TN={tn}")
    print(f"Precision: {precision:.3f}   Recall: {recall:.3f}   F1: {f1:.3f}")

    print("\nRecall by fault type (of TRUE anomalies of that type, how many did we catch):")
    for ft in fault_type[ground_truth].unique():
        mask = ground_truth & (fault_type == ft)
        if mask.sum() == 0:
            continue
        caught = (predicted & mask).sum()
        print(f"  {ft:<28} {caught}/{mask.sum()} caught  ({caught/mask.sum():.1%})")

    return {"precision": precision, "recall": recall, "f1": f1, "tp": tp, "fp": fp, "fn": fn, "tn": tn}


def evaluate_all(labeled_files: list[Path], artifact: dict, metadata: pd.DataFrame = None) -> dict:
    frames = []
    for path in labeled_files:
        d = pd.read_csv(path, parse_dates=["timestamp"])
        if "is_anomaly" not in d.columns:
            raise ValueError(f"{path.name} has no is_anomaly column -- is this actually a _labeled.csv?")
        d["__source_file"] = path.name
        frames.append(d)
    df_full = pd.concat(frames, ignore_index=True)

    has_fault_type = "fault_type" in df_full.columns
    label_cols = ["station_id", "timestamp", "is_anomaly", "__source_file"] + (["fault_type"] if has_fault_type else [])
    labels = df_full[label_cols].copy()
    labels["is_anomaly"] = labels["is_anomaly"].fillna(False).astype(bool)
    labels["fault_type"] = labels["fault_type"].fillna("none") if has_fault_type else "none"

    df = df_full.drop(columns=["is_anomaly", "fault_type", "__source_file"], errors="ignore")

    # PASS 1: no exclusion -- a real fault's own extreme raw values sit
    # inside every recovery reading's 48h rolling window for up to 48h
    # after the fault ends, inflating those CLEAN recovery rows' score.
    featured_p1, _, _, _, _, predicted_p1,_, _ = _featurize_and_score(df, metadata, artifact)

    # PASS 2: re-featurize using PASS 1's OWN PREDICTIONS (never ground
    # truth -- that would be look-ahead) as the exclusion mask,
    # approximating live detect.py/state.py's self-healing baseline.
    # This is an approximation, not causal-online-exact -- say so if
    # numbers are reported.
    df_pass2 = df.merge(
        featured_p1[["station_id", "timestamp"]].assign(__pass1_flag=predicted_p1),
        on=["station_id", "timestamp"], how="left",
    )
    df_pass2["__pass1_flag"] = df_pass2["__pass1_flag"].fillna(False)

    featured, model_pct, hard_fired, soft_fired, score_pct, predicted, n_dropped_total, soft_breakdown = \
        _featurize_and_score(df_pass2, metadata, artifact, mask_col="__pass1_flag")

    print(f"\n(Two-pass eval -- Finding 1 mitigation: pass 1 flagged {int(predicted_p1.sum())} rows; "
          f"after re-baselining around pass 1's own flags, pass 2 flags {int(predicted.sum())} rows. "
          f"Numbers below are PASS 2.)")

    featured = featured.merge(labels, on=["station_id", "timestamp"], how="left")
    featured["is_anomaly"] = featured["is_anomaly"].fillna(False).astype(bool)
    featured["fault_type"] = featured["fault_type"].fillna("none")
    featured["__source_file"] = featured["__source_file"].fillna("unknown")
    featured["__predicted"] = predicted
    featured["__score_pct"] = score_pct

    print("\n--- PER-STATION MODEL SCORE PROFILE (clean rows only) ---")
    for station, group in featured[~featured["is_anomaly"]].groupby("station_id"):
        idx = group.index
        mp = model_pct[idx]
        print(f"  {station:<16} mean={mp.mean():.1f}  pct>=55: {(mp>=55).mean():.1%}  n={len(group)}")

    # --- FINDING 2 DIAGNOSTIC: per-station feature means on clean rows,
    # to isolate which feature is driving BHO/MUM-007's elevation. ---
    print("\n--- PER-STATION FEATURE MEAN COMPARISON (clean rows) ---")
    check_cols = ["spatial_temp_inconsistency", "spatial_pressure_inconsistency",
                  "spatial_humidity_inconsistency", "pressure_inconsistency",
                  "temp_humidity_coupling_signal", "temp_rolling_std",
                  "pressure_rolling_std", "humidity_rolling_std"]
    clean_only = featured[~featured["is_anomaly"]]
    for col in check_cols:
        print(f"\n  {col}:")
        for station, group in clean_only.groupby("station_id"):
            print(f"    {station:<16} mean={group[col].mean():.3f}  std={group[col].std():.3f}")
    print("--- END DIAGNOSTIC ---\n")

    clean_mask = ~featured["is_anomaly"]
    print(f"\n--- FP SOURCE BREAKDOWN (on {int(clean_mask.sum())} ground-truth-clean rows) ---")
    print(f"hard_fired on clean rows:  {int((hard_fired & clean_mask).sum())}")
    print(f"soft_fired on clean rows:  {int((soft_fired & clean_mask).sum())}")
    print(f"  -- frozen: {int((soft_breakdown['frozen'] & clean_mask).sum())}")
    print(f"  -- drift:  {int((soft_breakdown['drift'] & clean_mask).sum())}")
    print(f"  -- spike:  {int((soft_breakdown['spike'] & clean_mask).sum())}")
    print(f"model_pct>={MODEL_ONLY_THRESHOLD} on clean, no rule fired at all: "
          f"{int(((model_pct >= MODEL_ONLY_THRESHOLD) & ~hard_fired & ~soft_fired & clean_mask).sum())}")
    print("--- END DIAGNOSTIC ---\n")
    print("\n--- MODEL_PCT DISTRIBUTION: soft_fired split by true label ---")

    soft_mask = soft_fired.to_numpy(dtype=bool)
    clean_mask_np = (~featured["is_anomaly"]).to_numpy(dtype=bool)
    true_anomaly_mask_np = featured["is_anomaly"].to_numpy(dtype=bool)

    soft_clean = model_pct[soft_mask & clean_mask_np]
    soft_true = model_pct[soft_mask & true_anomaly_mask_np]

    print(
        f"soft_fired on CLEAN rows: "
        f"n={len(soft_clean)}  "
        f"mean={soft_clean.mean():.1f}  "
        f"median={np.median(soft_clean):.1f}  "
        f"pct<20={(soft_clean < 20).mean():.1%}  "
        f"pct<35={(soft_clean < 35).mean():.1%}  "
        f"pct<50={(soft_clean < 50).mean():.1%}  "
        f"pct<65={(soft_clean < 65).mean():.1%}"
    )

    print(
        f"soft_fired on TRUE anomaly rows: "
        f"n={len(soft_true)}  "
        f"mean={soft_true.mean():.1f}  "
        f"median={np.median(soft_true):.1f}  "
        f"pct<20={(soft_true < 20).mean():.1%}  "
        f"pct<35={(soft_true < 35).mean():.1%}  "
        f"pct<50={(soft_true < 50).mean():.1%}  "
        f"pct<65={(soft_true < 65).mean():.1%}"
    )

    print("--- END MODEL_PCT DIAGNOSTIC ---\n")
    print(f"\n{'='*60}\nOVERALL (all {len(labeled_files)} files combined, two-pass, real spatial context)\n{'='*60}")
    results = {"__overall__": _score_and_report(featured, "ALL FILES COMBINED", n_dropped_total)}

    for source_file, group in featured.groupby("__source_file"):
        n_in_file = int((df_full["__source_file"] == source_file).sum())
        n_dropped_file = n_in_file - len(group)
        results[source_file] = _score_and_report(group.reset_index(drop=True), source_file, n_dropped_file)

    return results


if __name__ == "__main__":
    if not ARTIFACTS_PATH.exists():
        raise FileNotFoundError(f"No trained model at {ARTIFACTS_PATH} -- run model/train.py first.")
    artifact = joblib.load(ARTIFACTS_PATH)
    if "rule_thresholds" not in artifact:
        raise KeyError(
            "Loaded artifact has no 'rule_thresholds' key -- it was saved by an older "
            "train.py, before calibrate_rule_thresholds() was added. Retrain first."
        )

    metadata_path = DATA_DIR / "stations_metadata.csv"
    metadata = pd.read_csv(metadata_path) if metadata_path.exists() else None

    labeled_files = sorted(DATA_DIR.glob("*_labeled.csv"))
    if not labeled_files:
        print(f"No *_labeled.csv files found in {DATA_DIR} -- run anomaly_injector.py first.")
    else:
        print(f"Evaluating against {len(labeled_files)} labeled file(s), combined for real "
              f"spatial context. Remember: this measures detection of OUR OWN injected fault "
              f"patterns -- see the module docstring's overfitting caution before reporting "
              f"these numbers.")
        evaluate_all(labeled_files, artifact, metadata)